add ADR for no internal prefixes
ga4gh/seqcol-spec pull request #42
Opened 2023-01-11 21:59 UTC by nsheff

Resolves half of #37

2023-01-25 15:28 UTC, nsheff commented
1. "external" can mean 2 things: A) content provided to us; B) the way our identifiers are used externally. Should be clarified.
2. We need more explicit direction on how/when content provided to us should be prefixed.

2023-05-17 13:32 UTC, tcezard approved these changes

2023-05-17 13:32 UTC, tcezard commented on docs/decision_record.md
> +## 2023-XX-XX - Internal identifiers SHOULD NOT be prefixed
Should update the date

2023-05-17 14:02 UTC, sveinugu requested changes
I am happy with the pet of the ADR that refer to internal identifiers, however I think it is premature to approve the part on external without knowing the conclusion of a) whether refget digests must be prefixed or not, and b) any top-level decision on GA4GH CURIE namespacing. 

If for instance it is decided to use the same namespace for seqcol and refget identifiers, I would argue
that the refget identifiers should NOT be prefixed inside a seqcol (as the namespace would is the default one). 

In addition one could also add an explicit requirement that values that are defined as CURIEs (in the schema?) from other namespace MUST include the namespace prefix.

2023-07-12 14:24 UTC, nsheff commented
decision: sequences *should not* be prefixed with `ga4gh:`, but they *should* be prefixed with `SQ.`

2023-07-26 12:35 UTC, nsheff commented
Ok, I added this statement:

> More specifically, for refget, there are two types of prefix: the namespace prefix (`ga4gh:`) and type type prefix (`SQ.`). Right now, the refget server requires you to have the type prefix to request a lookup; the refget protocol declares that this type prefix is *part of the identifier*. However, the `ga4gh:` prefix is more of a namespace prefix and is *not* required, and therefore not considered part of the identifier. Therefore, the seqcol `sequence` values would *include* the `SQ.` but not the `ga4gh:`.

Is that correct?

2023-07-27 11:38 UTC, merged